services:
  - type: web
    plan: free
    name: Telegram
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m Telegram 
    repo: https://github.com/TeamJapanese/The-Japanese  
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: STRING_SESSION
        sync: false
    autoDeploy: false
